# Generated by Django 4.1.2 on 2022-11-16 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendas_prod',
            options={'verbose_name': 'Produto da venda', 'verbose_name_plural': 'Produtos da venda'},
        ),
    ]
